### ISSUE TITLE
Configurable Column Selection in `esctl get` Command

### ISSUE THREAD

**Issue by fehmicansaglam** [fehmicansaglam/esctl#10]
**Description**

Implement a feature that allows users to specify the columns they want to see when they run `esctl get`. This can be done by extending the `esctl.yml` configuration file to include a `columns` section for each entity. The `columns` section should be a list of column headers that the user wants to see in the output of `esctl get`.

**Motivation**

As the project continues to grow and more columns are added, the output of `esctl get` is becoming increasingly crowded. To keep the output manageable and relevant to individual users, it would be beneficial to allow users to specify which columns they want to see in the output. 

**Additional Context**

Here's an example of how this might look in the `esctl.yml` configuration file:

```yml
clusters:
    - host: localhost
      name: cluster1
      port: 9200
      protocol: http
    - host: 127.0.0.1
      name: cluster2
      port: 9200
      protocol: http
current-cluster: cluster2
entities:
    nodes:
        columns: ["NAME", "IP", "NODE-ROLE", "HEAP-MAX", "CPU", "DISK-TOTAL"]
    # Other entities can also have their own `columns` sections
```

In this example, the `entities` section is a new addition to the configuration file. Under `entities`, there's a `nodes` section, which includes a `columns` section. The `columns` section lists the column headers that will be displayed when a user runs `esctl get nodes`. This concept can be extended to other entities like `indices`, `aliases`, etc.
