### ISSUE TITLE
Add Support for Multiple Elasticsearch Clusters in esctl Configuration

### ISSUE THREAD

**Issue by fehmicansaglam** [fehmicansaglam/esctl#7]
**Description**

As an improvement to the esctl, it would be beneficial to add support for managing multiple Elasticsearch clusters in the configuration. Presently, esctl accepts parameters like host, port, and protocol to specify the Elasticsearch node to connect to. It would be helpful if we could specify these details for multiple clusters in a YAML configuration file, and then have an option to switch between these clusters. 

The configuration file should allow us to specify fields such as protocol, host, port, username, and password for each cluster. Host should be the only mandatory field, while protocol, port, username, and password should be optional with sensible defaults. Users should be able to choose their preferred cluster using a command line flag or a dedicated command like "esctl set-cluster <cluster>" to update the current cluster in the configuration.

**Motivation**

Working with multiple Elasticsearch clusters is a common scenario in many organizations. Being able to specify and switch between different clusters directly through esctl would make this tool even more powerful and convenient for its users.

The proposed feature aligns with the goals of the esctl project by improving its versatility and utility for various Elasticsearch use cases. It also promotes productivity by streamlining the process of switching between different Elasticsearch clusters.

**Additional Context**

An example configuration could look like this:

```yaml
clusters:
  - name: cluster1
    protocol: http
    host: es-cluster1.com
    port: 9200
    username: user1
    password: pass1
  - name: cluster2
    protocol: https
    host: es-cluster2.com
    port: 9300
    username: user2
    password: pass2
```

Users could then switch between clusters with a command such as:
```
esctl set-cluster cluster2
```
Or by setting a flag:
```
esctl --cluster cluster2 <command>
```

- If the user provides the Elasticsearch details through flags or environment variables, esctl could prioritize these details.
- If no flags or environment variables are provided, esctl could fall back to the configuration file.
- If no cluster is explicitly chosen, esctl will default to using the first cluster in the configuration file.
